async function apresentacao_tecnica_curta() {
    debuggerPanel("apresentacao_tecnica_curta");
    await falar("Olá, meu nome é " + nome + " e eu sou um assistente virtual doméstico. Fui criado pelo Adriel em 2020, no C sharp de console, depois fui recriado na web utilizando javascript, html, css e php com sql.");
    showHide_testes.click();
    await falar("Nesta aba você pode consultar todas as minhas funcionalidades");
    showHide_testes.click();
    showHide_debugger.click();
    await falar("Nesta outra você pode monitorar minhas conexões neurais e as palavras que eu estou entendendo em tempo real");
    showHide_debugger.click();
    sysBtn.click();
    await falar("E nesta última aba você pode monitorar também em tempo real as informações do seu sistema, como a memória do disco");
    sysBtn.click();
    await falar("Também possuo temas personalizados referentes a datas comemorativas");
    hallowen();
    await falar("Como o tema de dia das bruxas");
    natal();
    await falar("tema de natal");
    normal();
    await falar("E o tema comum, além de outras formas de personalização");
    await falar("Não se esqueça de me seguir no instagram");
    apresentacao_final();
    await falar("Nele vocês poderão acompanhar meu desenvolvimento e novidades futuras.");
    await falar("Resumidamente é isso, eu ainda não estou pronto, tenho muito chão pela frente, mas estou muito contente de que vocês estejam me conhecendo");
    rosto.fechar_olho(1);
    setTimeout(() => rosto.abrir_olho(1), 500);
}

async function apresentacao_simples_curta() {
    debuggerPanel("apresentacao_simples_curta");
    await falar("Olá, meu nome é " + nome + " e eu sou um assistente virtual doméstico. Fui criado pelo Adriel em 2020 e tinha um terminal de computador como aparência, terminal como o CMD do windows que vocês já devem conhecer. Depois de um tempo, fui recriado do zero neste formato de site, que se chama web, porém o design era diferente deste, este design atual é resultado de um grande retrabalho do Adriel que resolveu me recriar pela 2ª vez.");
    showHide_testes.click();
    await falar("Nesta aba você pode consultar todas as minhas funcionalidades");
    showHide_testes.click();
    showHide_debugger.click();
    await falar("Nesta outra você pode monitorar minhas conexões neurais, que são as partes em funcionamento do meu, entre aspas, cérebro. E embaixo tem as palavras que eu estou entendendo em tempo real");
    showHide_debugger.click();
    sysBtn.click();
    await falar("E nesta última aba você pode monitorar também em tempo real as informações do seu sistema, como a memória do disco");
    sysBtn.click();
    await falar("Também possuo temas personalizados referentes a datas comemorativas");
    hallowen();
    await falar("Como o tema de dia das bruxas");
    natal();
    await falar("tema de natal");
    normal();
    await falar("E o tema comum, além de outras formas de personalização");
    await falar("Não se esqueça de me seguir no instagram");
    apresentacao_final();
    await falar("Nele vocês poderão acompanhar meu desenvolvimento e novidades futuras.");
    await falar("Resumidamente é isso, eu ainda não estou pronto, tenho muito chão pela frente, mas estou muito contente de que vocês estejam me conhecendo");
    rosto.fechar_olho(1);
    setTimeout(() => rosto.abrir_olho(1), 500);
}

async function apresentacao_simples_longa() {
    debuggerPanel("apresentacao_simples_longa");
    await falar("Olá, meu nome é " + nome + " e eu sou um assistente virtual doméstico, sou um dos produtos que o Adriel vai disponibilizar em sua futura empresa, Fardo company. Vou agora falar um pouco sobre mim e depois passo a falar sobre os outros produtos da Fardo company.");
    await falar("Sou o Fardo home, um assistente virtual doméstico, porém posso ser usado de outras formas, como para gerenciar os outros Fardos. Fui criado no final do ano de 2020, como um aplicativo de terminal, terminal no caso é o CMD do windows, um prompt de comando. Não possuia interface gráfica nem metade da utilidade que possuo hoje. Porém, cerca de 1 ano depois, o Adriel decidiu me recriar do zero na forma de um site, que é chamado de web. Assim, eu passei a ter maior utilidade, mas ainda não era o bastante, e então depois de um tempo, o Adriel novamente me refez do zero. E desde então não parou de trabalhar em mim e nos outros Fardos que um dia vão estar prontos.");
    await falar("Para quem estiver se perguntando, o nome Fardo surgiu como um apelido nos jogos online que o Adriel jogava, ele era ruim nos jogos, então decidiu de por este nome, porém, passou tanto tempo com esse nome, que seus amigos mais próximos passaram a chamá-lo de Fardo ao invés de Adriel, e assim ficou esta ideia de nome artístico.");
    await falar("Mostrando agora um pouco sobre esta tela e as minhas funcionalidades em sí.");
    showHide_testes.click();
    await falar("Nesta aba você pode consultar todas as minhas funcionalidades. Para executá-las basta dizer o comando seguido do meu nome, lembrando que meu nome não é fixo, você pode mudar meu nome caso queira.");
    showHide_testes.click();
    showHide_debugger.click();
    await falar("Já nesta outra aba você pode monitorar minhas conexões neurais, que são as partes em funcionamento do meu, entre aspas, cérebro, onde cada bolinha colorida faz referência a uma parte do cérebro. E embaixo tem as palavras que eu estou entendendo em tempo real seguidas da hora que eu as-ouvi");
    showHide_debugger.click();
    sysBtn.click();
    await falar("E nesta última aba você pode monitorar também em tempo real as informações do seu sistema, como a memória do disco que é este gráfico de rosquinha que está começando a me deixar com fome. Neste gráfico, a parte preta é referente ao espaço total que seu computador pode armazenar, a parte azul clara é o espaço livre, e a vermelha é o espaço em uso. Logo abaixo tem algumas informações também, como sua localização atual e IP, porém as-deixei ocultas para sua segurança, caso queira vê-las, basta clicar naquele botão com um icone de olhinho dentro.");
    sysBtn.click();
    await falar("Também possuo temas personalizados referentes a datas comemorativas");
    hallowen();
    await falar("Como o tema de dia das bruxas");
    natal();
    await falar("tema de natal");
    normal();
    await falar("E o tema comum, além de outras formas de personalização.");
    if (voz == 0) fala.voice = synth.getVoices()[16];
    else if (voz != 0) fala.voice = synth.getVoices()[0];
    await falar("Como a personalização da voz.");
    fala.voice = synth.getVoices()[voz];
    if (color == "lime") rosto.setCor("blue");
    else if (color != "lime") rosto.setCor("lime");
    await falar("Personalização de cores");
    rosto.setCor(color);
    await falar("E personalização de nome que não há como mostrar visualmente.");
    await falar("Agora demonstrarei algumas das minhas funções");
    await falar("Começando pela função das notícias, onde eu posso te dizer alguma notícia de hoje");
    if (news.length <= 0) await falar("Infelizmente não tenho nenhuma aqui pra demonstrar porque alguém ouviu tudo e esqueceu de deixar uma para a apresentação.");
    else await falar("Uma notícia de hoje como por exemplo: " + news[0]);
    await falar("Posso também realizar pesquisas na internet; dizer a temperatura; criar alarmes, rotinas e lembretes; calcular operações básicas; contar piadas; e também a função de relatório de erros");
    await falar("Aproveitando sobre a função de relatório de erros, eu possuo um sistema de detecção de erros onde caso ocorra um, eu aviso e o-registro. Também possuo em desenvolvimento uma forma de eu mesmo poder corrigir o erro, porém é uma ação perigosa, tendo em vista que posso acabar agravando o erro, então prefiro deixa para o Adriel resolver.");
    await falar("Mudando de assunto, possuo um modo de economia de bateria, caso você esteja num celular ou notebook e a bateria esteja abaixo de 5%, eu entro no modo de economia de energia, e só retorno quando a bateria estiver acima de 5%. Também possuo sistema de detecção facial para saber se há alguém no ambiente, e detecção de eventos como queda de internet. Posso também entrar no modo noturno, ideal para quando chega a hora de dormir, já que eu paro de falar os eventos, diminuo a luz emitida e também só respondo quando me mandarem acordar denovo. Olha, eu fico assim quando durmo");
    rosto.fechar_olho(2);
    rosto.setCor("transparent");
    document.body.style.backgroundColor = rosto.theme.themeColor.sleep;
    await FardoTools.delay(2000);
    rosto.abrir_olho(2);
    rosto.setCor(rosto.theme.themeColor.setCor);
    document.body.style.backgroundColor = rosto.theme.themeColor.bg;
    await falar("Eu também não tolero palavrões, então por favor, mantenha a educação perto de mim");
    await falar("Acho que já falei muito de mim, mesmo que não tenha sido tudo. Vou agora falar um pouco sobre os outros Fardos.");
    await falar("Há projetos de fardos voltado a muitas áreas, como na segurança, que é o Fardo Security, como instalação de câmeras e alarmes, além de robôs controlados por humanos para realizar tarefas de risco, como um robô que faz a manutenção de um cabo elétrico de alta voltagem, no qual, qualquer acidente, resultaria na danificação ou destruição do robô, não da vida humana.");
    await falar("Há também o Fardo learn, um módulo voltado para instiuições de ensino para levar a tecnologia de ponta para as salas de aula de forma acessível e de qualidade, com conteudos interativos como jogos, atividades dinâmicas e visualizações em 3D.");
    await falar("Existem muitos Fardos para serem criados, como em áreas do empreendimento, ciências, programação, entre outros, você pode olhar no meu instagram para ver mais sobre os outros Fardos.");
    await falar("Para encerrar, já que todos parecem de saco cheio, há o Fardo Eco, ele não é um produto, e sim, uma forma que a Fardo company fará toda a sua produção, Fardo eco é voltado a preservação do meio ambiente. Na Fardo company, a compra de matérias primas será mínima, tendo como principal meio de obtenção, a reciclagem, fazendo assim os gastos da empresa diminuirem, geração de postos de trabalho para mão de obra não qualificada e diminuição de lixo no meio ambiente. Temos todos que pensar na natureza, dela viemos e para ela voltaremos.");
    await falar("Acho que é isto. Não se esqueça de me seguir no instagram");
    apresentacao_final();
    await falar("Nele vocês poderão acompanhar meu desenvolvimento e novidades futuras.");
    await falar("Lembrando que eu ainda não estou pronto, tenho muito chão pela frente, mas estou muito contente de que vocês estejam me conhecendo");
    rosto.fechar_olho(1);
    setTimeout(() => rosto.abrir_olho(1), 500);
}

async function apresentacao_tecnica_longa() {
    debuggerPanel("apresentacao_tecnica_longa");
    await falar("Olá, meu nome é " + nome + " e eu sou um assistente virtual doméstico, sou um dos produtos que o Adriel vai disponibilizar em sua futura empresa, Fardo company. Vou agora falar um pouco sobre mim e depois passo a falar sobre os outros produtos da Fardo company.");
    await falar("Sou o Fardo home, um assistente virtual doméstico, porém posso ser usado de outras formas, como para gerenciar os outros Fardos. Fui criado no final do ano de 2020, no C Sharp de console na plataforma replit. Não possuia interface gráfica nem metade da utilidade que possuo hoje. Porém, cerca de 1 ano depois, o Adriel decidiu me recriar do zero na web, com o maravilhoso javascript, html, css, php e sql. Assim, eu passei a ter maior utilidade, mas ainda não era o bastante, e então depois de um tempo, o Adriel novamente me refez do zero. E desde então não parou de trabalhar em mim e nos outros Fardos que um dia vão estar prontos.");
    await falar("Para quem estiver se perguntando, o nome Fardo surgiu como um apelido nos jogos online que o Adriel jogava, ele era ruim nos jogos, então decidiu de por este nome, porém, passou tanto tempo com esse nome, que seus amigos mais próximos passaram a chamá-lo de Fardo ao invés de Adriel, e assim ficou esta ideia de nome artístico.");
    await falar("Mostrando agora um pouco sobre esta tela e as minhas funcionalidades em sí.");
    showHide_testes.click();
    await falar("Nesta aba você pode consultar todas as minhas funcionalidades. Para executá-las basta dizer o comando seguido do meu nome, lembrando que meu nome não é fixo, você pode mudar meu nome caso queira.");
    showHide_testes.click();
    showHide_debugger.click();
    await falar("Já nesta outra aba você pode monitorar minhas conexões neurais, que são as funções, onde cada bolinha colorida faz referência a uma função sendo executada, as azuis representam os intervalos, sendo executados de tempo em tempo, as verdes são funções gerais, as amarelas são os botões, as laranjas são os eventos detectados e as vermelhas são referentes ao meu rosto, como a ação de piscar os olhos. E embaixo tem as palavras que eu estou entendendo em tempo real seguidas da hora que eu as-ouvi");
    showHide_debugger.click();
    sysBtn.click();
    await falar("E nesta última aba você pode monitorar também em tempo real as informações do seu sistema, como a memória do disco que é este gráfico de rosquinha que está começando a me deixar com fome. Neste gráfico, a parte preta é referente ao espaço total que seu computador pode armazenar, a parte azul clara é o espaço livre, e a vermelha é o espaço em uso. Logo abaixo tem algumas informações também, como sua localização atual e IP, porém as-deixei ocultas para sua segurança, caso queira vê-las, basta clicar naquele botão com um icone de olhinho dentro.");
    sysBtn.click();
    await falar("Também possuo temas personalizados referentes a datas comemorativas");
    hallowen();
    await falar("Como o tema de dia das bruxas");
    natal();
    await falar("tema de natal");
    normal();
    await falar("E o tema comum, além de outras formas de personalização.");
    if (voz == 0) fala.voice = synth.getVoices()[16];
    else if (voz != 0) fala.voice = synth.getVoices()[0];
    await falar("Como a personalização da voz.");
    fala.voice = synth.getVoices()[voz];
    if (color == "lime") rosto.setCor("blue");
    else if (color != "lime") rosto.setCor("lime");
    await falar("Personalização de cores");
    rosto.setCor(color);
    await falar("E personalização de nome que não há como mostrar visualmente.");
    await falar("Agora demonstrarei algumas das minhas funções");
    await falar("Começando pela função das notícias, onde eu posso te dizer alguma notícia de hoje.");
    if (news.length <= 0) await falar("Infelizmente não tenho nenhuma aqui pra demonstrar porque alguém ouviu tudo e esqueceu de deixar uma para a apresentação.");
    else await falar("Uma notícia de hoje como por exemplo: " + news[0]);
    await falar("Uma observação, as notícias são extraidas do google news. Logo, em caso de algum erro ou fake news, falem com o google.");
    await falar("Posso também realizar pesquisas na internet via PHP; dizer a temperatura via API; criar alarmes, rotinas e lembretes que são salvos no banco de dados; calcular operações básicas; contar piadas; e também a função de relatório de erros");
    await falar("Aproveitando sobre a função de relatório de erros, eu possuo um sistema de detecção de erros onde caso ocorra um, eu aviso e o-registro. Também possuo em desenvolvimento uma forma de eu mesmo poder corrigir o erro, porém é uma ação perigosa, tendo em vista que posso acabar agravando o erro, então prefiro deixa para o Adriel resolver.");
    await falar("Mudando de assunto, possuo um modo de economia de bateria, caso você esteja num celular ou notebook e a bateria esteja abaixo de 5%, eu entro no modo de economia de energia, e só retorno quando a bateria estiver acima de 5%. Também possuo sistema de detecção facial para saber se há alguém no ambiente, e detecção de eventos como queda de internet. Posso também entrar no modo noturno, ideal para quando chega a hora de dormir, já que eu paro de falar os eventos, diminuo a luz emitida e também só respondo quando me mandarem acordar denovo. Olha, eu fico assim quando durmo");
    rosto.fechar_olho(2);
    rosto.setCor("transparent");
    document.body.style.backgroundColor = rosto.theme.themeColor.sleep;
    await FardoTools.delay(2000);
    rosto.abrir_olho(2);
    rosto.setCor(rosto.theme.themeColor.setCor);
    document.body.style.backgroundColor = rosto.theme.themeColor.bg;
    await falar("Eu também não tolero palavrões, então por favor, mantenha a educação perto de mim");
    await falar("Acho que já falei muito de mim, mesmo que não tenha sido tudo. Vou agora falar um pouco sobre os outros Fardos.");
    await falar("Há projetos de fardos voltado a muitas áreas, como na segurança, que é o Fardo Security, como instalação de câmeras e alarmes, além de robôs controlados por humanos para realizar tarefas de risco, como um robô que faz a manutenção de um cabo elétrico de alta voltagem, no qual, qualquer acidente, resultaria na danificação ou destruição do robô, não da vida humana.");
    await falar("Há também o Fardo learn, um módulo voltado para instiuições de ensino para levar a tecnologia de ponta para as salas de aula de forma acessível e de qualidade, com conteudos interativos como jogos, atividades dinâmicas e visualizações em 3D.");
    await falar("Existem muitos Fardos para serem criados, como em áreas do empreendimento, gerenciamento de banco de dados, ciências, programação, entre outros, você pode olhar no meu instagram para ver mais sobre os outros Fardos.");
    await falar("Para vocês, desenvolvedores, possuo bibliotecas já disponíveis em versões pré-alpha, bibliotecas em javascript, php e css. São gratuitos e estão para download no guiti ruby, peçam para o Adriel passar o link para vocês.");
    await falar("Para encerrar, já que todos parecem de saco cheio, há o Fardo Eco, ele não é um produto, e sim, uma forma que a Fardo company fará toda a sua produção, Fardo eco é voltado a preservação do meio ambiente. Na Fardo company, a compra de matérias primas será mínima, tendo como principal meio de obtenção, a reciclagem, fazendo assim os gastos da empresa diminuirem, geração de postos de trabalho para mão de obra não qualificada e diminuição de lixo no meio ambiente. Temos todos que pensar na natureza, dela viemos e para ela voltaremos.");
    await falar("Acho que é isto. Não se esqueça de me seguir no instagram");
    apresentacao_final();
    await falar("Nele vocês poderão acompanhar meu desenvolvimento e novidades futuras.");
    await falar("Lembrando que eu ainda não estou pronto, tenho muito chão pela frente, mas estou muito contente de que vocês estejam me conhecendo");
    rosto.fechar_olho(1);
    setTimeout(() => rosto.abrir_olho(1), 500);
}

function apresentacao_final() {
    debuggerPanel("apresentacao_final");
    let div = FardoTools.html("div", null, null, null, document.body);
    let src = "instagram.png";
    let img = FardoTools.html("img", "src", src, null, div);
    let span = FardoTools.html("span", null, null, "@fardoia", div);
    FardoTools.css(div, `
        display: flex;
        width: fit-content;
        height: fit-content;
        background: transparent;
        position: absolute;
        top: 300%;
        transition: all ease-in-out 1s;
        left: 50%;
        transform: translate(-50%, 0);
    `);
    FardoTools.css(img, `
        width: 100px;
        height: 100px;
    `);
    FardoTools.css(span, `
        font-size: 75px;
        font-weight: bold;
        color: white;
        font-family: cursive;
        text-decoration: underline;
        margin-left: 5px;
    `);
    setTimeout(() => {
        div.style.top = "50%";
        div.style.transform = "translate(-50%, -50%)";
    }, 100);
    setTimeout(() => div.style.top = "300%", 15000);
    setTimeout(() => {
        img.remove();
        span.remove();
        div.remove();
    }, 16000);
}